name: mega_grpc
services:
  user_service_db:
    image: postgres:15
    command: -p ${POSTGRES_PORT}
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - user_service_db_data:/var/lib/postgresql/data
    expose:
      - ${POSTGRES_PORT}
    networks:
      - user_service_net
    env_file:
      - ./.env
    healthcheck:
      test: ["CMD", "pg_isready", "--dbname=${POSTGRES_DB}", "--username=${POSTGRES_USER}", "--port=${POSTGRES_PORT}"]
      interval: 5s
      timeout: 10s
      retries: 120

  user_service_redis:
    image: redis:7
    command: ["--port", "${REDIS_PORT}", "--save", "60", "1", "--loglevel", "warning"]
    expose:
      - ${REDIS_PORT}
    volumes:
      - user_service_redis_data:/data
    networks:
      - user_service_net
    env_file:
      - ./.env
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 5s
      timeout: 10s
      retries: 120

  user_service:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/user_service
    expose:
      - ${GRPC_PORT}
      - ${APP_PORT}
    networks:
      - user_service_net
      - services_net
    env_file:
      - ./.env
    depends_on:
      user_service_db:
        condition: service_healthy
      user_service_redis:
        condition: service_healthy
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 30

networks:
  user_service_net:
    name: user_service_net
  services_net:
    name: services_net

volumes:
    user_service_db_data:
      name: user_service_db_data
    user_service_redis_data:
      name: user_service_redis_data
